export const RECOIL_KEY = {
  AUTH_LOGIN_FORM_KEY: 'auth/AUTH_LOGIN_FORM_KEY',
  AUTH_REGISTER_FROM_KEY: 'auth/AUTH_REGISTER_FROM_KEY',
  AUTH_LOGIN: 'auth/AUTH_LOGIN',
  AUTH_REGISTER: 'auth/AUTH_REGISTER',

  USER_DATA: 'user/USER_DATA',
  USER_QUERY: 'user/USER_QUERY',

  EDITOR_DATA: 'write/EDITOR_DATA',
  EDITOR_TAGS_DATA: 'write/EDITOR_TAGS_DATA',

  LIST_POSTS_DATA: 'posts/LIST_POSTS_DATA',
  LIST_PAGINATION_DATA: 'posts/LIST_PAGINATION_DATA',
  LIST_POSTS_QUERY: 'posts/LIST_POSTS_QUERY',

  ORIGINAL_POST_DATA: 'post/ORIGINAL_POST_DATA',

  READ_POST_DATA: 'post/READ_POST_DATA',
  READ_POST_QUERY: 'post/READ_POST_QUERY',
};

export const STORAGE_KEY = {
  BLOG_USER_DATA: '@@blog/user',
};
